#pragma once

#define IDR_SETTINGS_PAGE_XAML 201
#define IDR_LORA_DIALOG_XAML 202
#define IDR_LORA_SELECTION_XAML 203
#define IDR_CUSTOM_NAME_ROW_XAML 204
#define IDR_CUSTOM_NAME_READING_XAML 205
#define IDR_CUSTOM_NAME_WARNING_XAML 206
#define IDR_LORA_RUBY_CELL_XAML 207
#define IDR_LORA_ITEM_TOOLTIP_XAML 208
#define IDR_LORA_TRAINING_ITEM_XAML 209
